[package]
name = "vk_openxr_app"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
openxr = "0.19.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
vulkano = "0.35.1"
